@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class AddressBook
Class Model
Class ModelManager
Class UserPrefs
Interface TagManager <<Interface>>
Class TagManager
Class SortedList

Class TagManagerImpl

Package Person {
Class Person
Class Address
Class Email
Class Name
Class Phone
Class UniquePersonList
}

Package Person-Tag-Integration {
Class ContactTagIntegrationManager
}

Package Tag {
Abstract Class TagTree
Class TagTreeImpl
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook -down-> "1" TagManager
TagManagerImpl .up.|> TagManager
TagManagerImpl -down-> "*" Tag
TagManagerImpl -right-> "*" Person

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager --> "1" AddressBook
ModelManager -left-> "1" UserPrefs
ModelManager -left-> "1" ContactTagIntegrationManager
ModelManager -left-> "1" TagTree
ModelManager -->"1" SortedList

SortedList --> "*" Person
SortedList ..> UniquePersonList : Uses data from >

ContactTagIntegrationManager --> "1" TagTree
ContactTagIntegrationManager --> "1" AddressBook

TagTreeImpl -up-|> TagTree
TagTreeImpl -down-> "*" Tag

AddressBook *--> "1" UniquePersonList
UniquePersonList --> "*" Person
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person -down-> "*" Tag

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

@enduml
