@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":SortEventCommandParser" as SortEventCommandParser LOGIC_COLOR
participant "sortEventCommand:SortEventCommand" as SortEventCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("sort -e 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("sort -e 1")
activate AddressBookParser

create SortEventCommandParser
AddressBookParser -> SortEventCommandParser
activate SortEventCommandParser

SortEventCommandParser --> AddressBookParser
deactivate SortEventCommandParser

AddressBookParser -> SortEventCommandParser : parse("1")
activate SortEventCommandParser

create SortEventCommand
SortEventCommandParser -> SortEventCommand
activate SortEventCommand

SortEventCommand --> SortEventCommandParser : sortEventCommand
deactivate SortEventCommand

SortEventCommandParser --> AddressBookParser : sortEventCommand
deactivate SortEventCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SortEventCommandParser -[hidden]-> AddressBookParser
destroy SortEventCommandParser

AddressBookParser --> LogicManager : sortEventCommand
deactivate AddressBookParser

LogicManager -> SortEventCommand : sortEventCommand.execute(model)
activate SortEventCommand

SortEventCommand -> Model : sortEvent(chooseComparator(1))
activate Model

Model --> SortEventCommand
deactivate Model

create CommandResult
SortEventCommand -> CommandResult
activate CommandResult

CommandResult --> SortEventCommand
deactivate CommandResult

SortEventCommand --> LogicManager : result
deactivate SortEventCommand

[<--LogicManager
deactivate LogicManager
@enduml
