@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface ManagementClassStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonManagementClassStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> ManagementClassStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonManagementClassStorage .left.|> ManagementClassStorage
JsonManagementClassStorage .down.> JsonSerializableManagementClass
JsonSerializableManagementClass .right.> JsonAdaptedXYZData
JsonAdaptedXYZData .right.> JsonAdaptedABCData

note bottom of ManagementClassStorage : ManagementClass = \nAddressBook,\nTagTree, Calendar

note "XYZData/ABCData refers to any basic\ndata type like Tag, Person, Event, etc." as tagNote
tagNote .. JsonAdaptedXYZData
tagNote .. JsonAdaptedABCData

@enduml
