@startuml
start
:User executes **view -t** command with **tag** input;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([tag relations found for **tag**])
: Graph updates its nodes and edges to those related to **tag**;
: Layout algorithm assigns coordinates for graph nodes;
: Graph layout is shown in a pop-up window;
else ([no tag relations found])
: Blank pop-up window shown;
endif
: User closes window;

stop
@enduml
